version: '2.1'

services:
  api-gateway:
    image: andersonnapoleao/bank-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8443:8443"

  user-service:
    image: andersonnapoleao/bank-user-service:0.0.1-SNAPSHOT
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      timeout: 20s
      retries: 10

  eureka:
    image: andersonnapoleao/bank-service-registry:0.0.1-SNAPSHOT
    mem_limit: 512m
    ports:
      - "8761:8761"